import type { AuditReport } from "@/types/audit.types";
import { CATEGORY_LABELS, FRAMEWORK_CHECKPOINTS } from "@/data/framework";
import { formatBytes, formatMs } from "@/lib/utils/url";

export function generateMarkdownReport(report: AuditReport): string {
  const percentage = report.maxScore > 0 ? Math.round((report.overallScore / report.maxScore) * 100) : 0;
  const gradeLabel = {
    elite: "Elite (90%+)",
    good: "Good (70-89%)",
    "needs-work": "Needs Work (50-69%)",
    critical: "Critical Issues (<50%)",
  }[report.grade];

  let md = `# SEO Audit Report\n\n`;
  md += `**URL:** ${report.url}\n`;
  md += `**Domain:** ${report.domain}\n`;
  md += `**Date:** ${new Date(report.completedAt || report.startedAt).toLocaleString()}\n`;
  md += `**Audit:** Metaminds SEO Check (55 checkpoints)\n\n`;

  md += `## Executive Summary\n\n`;
  md += `**Overall Score:** ${report.overallScore} / ${report.maxScore} (${percentage}%) — **${gradeLabel}**\n\n`;
  md += `| Metric | Count |\n|--------|------:|\n`;
  md += `| Passed | ${report.summary.passed} |\n`;
  md += `| Warnings | ${report.summary.warnings} |\n`;
  md += `| Failed | ${report.summary.failed} |\n`;
  md += `| Manual Review | ${report.summary.manual} |\n`;
  md += `| Pages Audited | ${report.pagesAudited} |\n`;
  md += `| Total Pages Found | ${report.totalPagesFound} |\n\n`;

  if (report.summary.strengths.length > 0) {
    md += `### Strengths\n\n`;
    for (const s of report.summary.strengths) {
      md += `- ${s}\n`;
    }
    md += `\n`;
  }

  if (report.summary.topIssues.length > 0) {
    md += `### Priority Issues\n\n`;
    for (const issue of report.summary.topIssues) {
      md += `- ${issue}\n`;
    }
    md += `\n`;
  }

  md += `## Category Breakdown\n\n`;
  md += `| Category | Score | Max | % |\n|----------|------:|----:|--:|\n`;
  for (const cat of report.categoryScores) {
    md += `| ${cat.label} | ${cat.score} | ${cat.maxScore} | ${cat.percentage}% |\n`;
  }
  md += `\n`;

  md += `## Detailed Findings\n\n`;
  for (const cat of report.categoryScores) {
    md += `### ${cat.label}\n\n`;
    for (const check of cat.checks) {
      const cp = FRAMEWORK_CHECKPOINTS.find((f) => f.id === check.checkpointId);
      const icon = { pass: "✅", warn: "⚠️", fail: "❌", na: "➖", manual: "🔍" }[check.status];
      md += `#### ${icon} #${check.checkpointId}: ${cp?.name || "Check"}\n\n`;
      md += `- **Status:** ${check.status.toUpperCase()}\n`;
      md += `- **Priority:** ${cp?.priority || "N/A"}\n`;
      md += `- **Score:** ${check.score} / ${check.maxScore}\n`;
      md += `- **Finding:** ${check.message}\n`;
      if (check.recommendation) md += `- **Recommendation:** ${check.recommendation}\n`;
      if (check.evidence?.length) md += `- **Evidence:** ${check.evidence.join("; ")}\n`;
      if (check.affectedUrls?.length) {
        md += `- **Affected URLs:**\n`;
        for (const u of check.affectedUrls.slice(0, 10)) {
          md += `  - ${u}\n`;
        }
      }
      md += `\n`;
    }
  }

  md += `## Per-Page Results\n\n`;
  for (const page of report.pageResults) {
    md += `### ${page.url}\n\n`;
    md += `- HTTP ${page.statusCode} | ${formatMs(page.responseTimeMs)} | ${formatBytes(page.pageSizeBytes)}\n`;
    if (page.issues.length > 0) {
      md += `\n**Issues:**\n`;
      for (const issue of page.issues) {
        md += `- ${issue}\n`;
      }
    } else {
      md += `\nNo issues found on this page.\n`;
    }
    md += `\n`;
  }

  md += `---\n\n`;
  md += `*Generated by Metaminds SEO Check*\n`;

  return md;
}
